version: '3.8'

services:
  ai-navi-backend-mock:
    build:
      context: ./ai-navi-backend-mock
      dockerfile: Dockerfile
      target: production
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - PORT=3001
      - HOST=0.0.0.0
      - CORS_ORIGIN=http://localhost:3000,http://localhost:5173,http://localhost:8080,http://127.0.0.1:8080
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/ai-navi/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    
  ai-navi-backend-mock-dev:
    build:
      context: ./ai-navi-backend-mock
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3002:3001"
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - PORT=3001
      - HOST=0.0.0.0
    volumes:
      - ./ai-navi-backend-mock:/app
      - /app/node_modules
    profiles:
      - dev